/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:24dba94e-d3fb-48a5-8823-464b67f80700",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_43JfAZdom",
    "aws_user_pools_web_client_id": "6e3i7qjuhjpmho9oefpn6opb3p",
    "oauth": {}
};


export default awsmobile;
