/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://qcqozpohq5g4xfxqiiuckm7afi.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-c6nwptc4yvas3gmbp4un3l2lma",
    "aws_user_files_s3_bucket": "ttcms59df1bc35ac841f1a7fac44acaeba61d12605-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
